version: "3.8"

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - infra_net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    networks:
      - infra_net

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    ports:
      - "61208:61208"
    pid: host
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - infra_net
      
  cloudflare-ddns-blitzc0de:
    image: oznu/cloudflare-ddns:latest
    container_name: cf-ddns-blitzc0de
    restart: unless-stopped
    environment:
      - API_KEY=${TOKEN_CLOUDFLARE}
      - ZONE=blitzc0de.com
      - SUBDOMAIN=*
      - PROXIED=true
    networks:
      - infra_net

  cloudflare-ddns-santaelena:
    image: oznu/cloudflare-ddns:latest
    container_name: cf-ddns-santaelena
    restart: unless-stopped
    environment:
      - API_KEY=${TOKEN_CLOUDFLARE}
      - ZONE=santaelena.gob.mx
      - SUBDOMAIN=*
      - PROXIED=true
    networks:
      - infra_net

  cloudflare-ddns-powersports:
    image: oznu/cloudflare-ddns:latest
    container_name: cf-ddns-powersports
    restart: unless-stopped
    environment:
      - API_KEY=${TOKEN_CLOUDFLARE}
      - ZONE=powersports.top
      - SUBDOMAIN=*
      - PROXIED=true
    networks:
      - infra_net

  cloudflare-ddns-torrenegra:
    image: oznu/cloudflare-ddns:latest
    container_name: cf-ddns-torrenegra
    restart: unless-stopped
    environment:
      - API_KEY=${TOKEN_CLOUDFLARE}
      - ZONE=torrenegraabogados.com
      - SUBDOMAIN=*
      - PROXIED=true
    networks:
      - infra_net

networks:
  infra_net:
    name: infra_net
    driver: bridge