version: '3.8'

services:
  mysql-dev:
    image: mysql:8.0
    container_name: mysql-dev
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Server*90
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-dev
      PMA_PORT: 3306
    depends_on:
      - mysql-dev
    volumes:
      - ./phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini