version: "3.9"

services:
  app:
    build: .
    container_name: ${PROJECT}_${MUNICIPIO_CODE}_app
    volumes:
      - ./host:/var/www/html:rw
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./apache.conf:/etc/apache2/conf-enabled/000-custom.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - infra_net
    labels:
      - "project=${PROJECT}"
      - "municipio=${MUNICIPIO_CODE}"
      - "municipio_nombre=${MUNICIPIO_NAME}"
      - "service=app"
      - "env=${ENV}"

  mysql:
    image: mysql:8.0
    container_name: ${PROJECT}_${MUNICIPIO_CODE}_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./dataBases:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    networks:
      - infra_net
    labels:
      - "project=${PROJECT}"
      - "municipio=${MUNICIPIO_CODE}"
      - "municipio_nombre=${MUNICIPIO_NAME}"
      - "service=database"
      - "env=${ENV}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT}_${MUNICIPIO_CODE}_pma
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - infra_net
    labels:
      - "project=${PROJECT}"
      - "municipio=${MUNICIPIO_CODE}"
      - "municipio_nombre=${MUNICIPIO_NAME}"
      - "service=admin"
      - "env=${ENV}"

volumes:
  db_data:

networks:
  infra_net:
    external: true