version: "3.9"
#Quitar los contanier_name en produccion?
services:

  php-apache:
    image: php:8.4-apache
    container_name: apchDev
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./Host:/var/www/html:rw
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./apache.conf:/etc/apache2/conf-enabled/000-custom.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    restart: always

  mysql:
    image: mysql:9.2
    container_name: sqlDev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dataBases:/docker-entrypoint-initdb.d #inicia las base de datos que estan en la carpeta
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admDev
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}

volumes:
  mysql_data: