upload_max_filesize = 512M
post_max_size = 512M
max_execution_time = 600
max_input_time = 600

display_errors = Off      ; No mostrar errores en el navegador
log_errors = On           ; Guardar errores en logs
error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING